[etcd]
node1 ansible_host=192.168.253.11
node2 ansible_host=192.168.253.12
node3 ansible_host=192.168.253.13

[patroni]
node1 ansible_host=192.168.253.11
node2 ansible_host=192.168.253.12
node3 ansible_host=192.168.253.13

[haproxy]
node1 ansible_host=192.168.253.11

[postgres_ha:children]
etcd
patroni
haproxy

[postgres_ha:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3
